#if !canImport(ObjectiveC)
import XCTest

extension TimeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TimeTests = [
        ("testMicroseconds", testMicroseconds),
        ("testMilliseconds", testMilliseconds),
        ("testNanoseconds", testNanoseconds),
        ("testSeconds", testSeconds)
    ]
}

extension TimerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TimerTests = [
        ("testTimerStop", testTimerStop),
        ("testTimerStopByDeinit", testTimerStopByDeinit)
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(TimeTests.__allTests__TimeTests),
        testCase(TimerTests.__allTests__TimerTests)
    ]
}
#endif
