#if !canImport(ObjectiveC)
import XCTest

extension TimePerformanceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TimePerformanceTests = [
        ("testPerformanceMachTime", testPerformanceMachTime),
        ("testPerformancePOSICGetTimeOfDayRaw", testPerformancePOSICGetTimeOfDayRaw),
        ("testPerformancePOSIXClock", testPerformancePOSIXClock),
        ("testPerformancePOSIXClockRaw", testPerformancePOSIXClockRaw),
        ("testPerformancePOSIXTimeOfDay", testPerformancePOSIXTimeOfDay),
        ("testPerformanceRawMachTime", testPerformanceRawMachTime)
    ]
}

extension TimeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TimeTests = [
        ("testMachTime", testMachTime),
        ("testPOSIXClock", testPOSIXClock),
        ("testPOSIXClockResolution", testPOSIXClockResolution),
        ("testPOSIXTimeOfDay", testPOSIXTimeOfDay)
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(TimePerformanceTests.__allTests__TimePerformanceTests),
        testCase(TimeTests.__allTests__TimeTests)
    ]
}
#endif
